use_frameworks!

target 'MultipartUpload_Example' do
  pod 'MultipartUpload', :path => '../'

  target 'MultipartUpload_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
